runtime: python39
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT main:app --timeout 180000 --workers 1 --threads 1
default_expiration: "300d 5h"

handlers:

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: .*
  script: main.app

instance_class: F1
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s


inbound_services:
- warmup
